### ISSUE TITLE
Period cannot deal with milliseconds

### ISSUE THREAD

**Issue by nettee** [rickb777/date#16] opened 2021-07-20 11:44 UTC
Test case:
```go
d := 10*time.Second + 10*time.Millisecond
p, _ := period.NewOf(d)
fmt.Println(d)
fmt.Println(p)
```

Output:
```
10.01s
PT10S
```

**Comment by jufemaiz** [comment] 2021-09-24 04:06
That's a feature, not a bug, of ISO8601.

```
PnYnMnDTnHnMnS
PnW

P is the duration designator (for period) placed at the start of the duration representation.
Y is the year designator that follows the value for the number of years.
M is the month designator that follows the value for the number of months.
W is the week designator that follows the value for the number of weeks.
D is the day designator that follows the value for the number of days.
T is the time designator that precedes the time components of the representation.
H is the hour designator that follows the value for the number of hours.
M is the minute designator that follows the value for the number of minutes.
S is the second designator that follows the value for the number of seconds.
```

Ref: https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by tstinebaugh-disco** [comment] 2022-01-15 00:44
It seems as though the ISO8601 duration standard supports various levels of precision surrounding milliseconds/nanoseconds. For example, XSD duration provides an example with milliseconds: http://books.xmlschemata.org/relaxng/ch19-77073.html

I created a PR with additional support for milliseconds. Please let me know if anyone likes my approach or wishes to refine it:
https://github.com/rickb777/date/pull/21

**Comment by rickb777** [comment] 2022-02-02 14:24
Thank you for your contribution.

I have decided to re-implement `period` rather than continue to patch it. The new period package will be https://github.com/rickb777/period. This will incorporates your remarks indirectly.

**Comment by jufemaiz** [comment] 2022-05-17 01:34
Probably worth closing with the recommendation to make use of the period package separately from the date package.

Thanks for your hard work on this @rickb777 !

**Comment by rickb777** [comment] 2023-11-15 14:25
Closing this issue now that the new period package https://github.com/rickb777/period is available

**Closed by rickb777** 2023-11-15 14:25 UTC
