### ISSUE TITLE
period: P7D is normalised to P1W even when normalisation is not set

### ISSUE THREAD

**Issue by khtufteland** [rickb777/date#12] opened 2020-10-09 16:05 UTC
I'm trying to parse the period `P7D` and I don't want any normalization.

```go
p, _ := period.Parse("P7D", false)
```

However, when I print this I get `P1W`.

It seems like this happens due to the code in the `String()` function:
https://github.com/rickb777/date/blob/d2bc4afd7cd27d07a25daa88f0ed92822a1ec19e/period/format.go#L107-L113

To me, this doesn't seem right. I believe that since `normalize` is deactivated should the result be `P7D`.

**Comment by rickb777** [comment] 2020-10-13 21:50
This is working as designed (and I hope as documented). It doesn't help you, but weeks are treated as 7-day multiples. The `Period` type does not store the number of weeks, only the number of days, so there is no way to avoid this apparent normalisation. (At least, not without a redesign; I have tried other approaches but the current one persists for now.)

**Comment by smyrman** [comment] 2020-10-14 15:36
Well, as `week` is not _stored_, would it make more sense to output `7D` instead of `1W` and onlly accept weeks when parsing (not when printing)?

**Comment by smyrman** [comment] 2020-10-14 15:37
I mean 8D is not transferred to 1W1D. Using only days in the output seams more consistent.

**Comment by rickb777** [comment] 2020-10-14 19:00
Fair point. It's an easy enough change and probably won't affect people adversely because both forms are equivalent.

**Comment by rickb777** [comment] 2020-10-14 21:06
The formatting code never outputs weeks unless there are no remaining days. So you won't (/shouldn't) ever see `1W1D` or anything like it, but you might see `52W`.

**Comment by rickb777** [comment] 2020-10-15 08:40
Because weeks are handled synthetically in `Period` (there is a `days` field but not one for weeks), it might be argued that the 'correct' solution is to add a `weeks` field and let normalisation handle the situation as it does with all the other fields.

I haven't decided whether I think this is the right choice yet.

**Comment by ololosha228** [comment] 2020-11-04 11:00
@rickb777 i agree with you, that `52W` is more readable, but i think that code must be predicted, so when i going to parse `364D` i expect `364D`, and not anything else)

Also, thanks for this package, i don't know why it has so few stars, it's sooooo useful

**Comment by smyrman** [comment] 2020-11-06 00:26
FYI, from Wikipedia, the ISO 8601 is documented as _eihter_ containing weeks, _or_ containing the other compoenents (years, months, days, hours, months etc):

```
P[n]Y[n]M[n]DT[n]H[n]M[n]S
P[n]W
P<date>T<time>
```

https://en.wikipedia.org/wiki/ISO_8601

In other words, mixing weeks with _anything_ is disallowed.

The ISO standard is also stating this: https://www.freestandardsdownload.com/iso-8601-1-2019-pdf.html

> The complete representation of the expression of a duration should be one of:
> a) ["P"][i]["Y"][i]["M"][i]["D"]["T"][i]["H"][i]["M"][i]["S"]
> b) ["P"][i]["W"]

Always sticking with "a" as the default option (e.g. for JSON encoding), would mean that `period.Period` would be _compatible_ with systems only accepting format "a" as input. a `StringWithWeeks` function could exist to get format b when explicitly wanted.

**Comment by rickb777** [comment] 2021-02-05 17:54
I have been working on a solution; it's not yet ready. Sorry.

**Comment by quenbyako** [comment] 2021-02-06 07:45
@rickb777 oh, you're alive! That's a good sign :laughing:

**Comment by rickb777** [comment] 2021-02-24 16:11
The branch https://github.com/rickb777/date/tree/direct-week-support carries the work done so far. There probably need to be API changes (implies v2 release).

1. `Parse()` and `MustParse()` have been altered to give clearer normalisation choices. Whilst this is not strictly necessary, it reduces the number of data conversions that would potentially be needed.
2. `Days()` and `Weeks()` now behave differently. This is a breaking change.
3. New method `DaysAndWeeks()` is a non-breaking change but behaves like `Days()` used to.
3. New function `NewYMWD()` is a non-breaking change.
4. New `function New2()` is rather rubbish but needed to avoid changing `New()`. Comments are requested on this @quenbyako 
5. New internal `weeks` field implements full support for weeks.
6. New internal `denormal` flag reduces the work needed if `Normalise()` is called repeatedly.

**Comment by quenbyako** [comment] 2021-02-24 16:24
@rickb777 Thanks a lot! You rock!

So i looked up into `New2` implementation and... Well... Am i able to make PR with refactoring this func? Also i don't agree with `New2` naming, honestly. It could be `NewV2` or, even better, `NewWithWeeks` which is, well, explicitly describing differents between these two funcs

**Comment by quenbyako** [comment] 2021-02-24 17:25
@rickb777 want to ask, why all values in `Period` time multiplied by 10? Looks pretty strange honestly

**Comment by smyrman** [comment] 2021-02-24 19:58
> New method DaysAndWeeks() is a non-breaking change but behaves like Days() used to.

This is _invalid_ according to the spec though... Both ISO and RFC. They only allow, as far as I can see, _either_ weeks, _or_ days, months, years etc.

**Comment by smyrman** [comment] 2021-02-24 20:05
Anyway, if there is a use case for the mixed format with weeks, keeping it is probably fine :-)

**Comment by smyrman** [comment] 2021-02-25 09:25
>NewWithWeeks which is, well, explicitly describing differents 

What about instead doing:

```go
func New(year int, month time.Month, day int) Date
func NewW(w int) Period
```
Drop `NewYMWD` and `New2` as they are initializers for an illegal format.

```go
type PeriodOfWeeks int
func (p PeriodOfWeeks) Date() Date
```

PS! As far as we are concerned (me and @khtufteland), the only _purpose_ of this issue is to _prevent_ automatic normalization into weeks. Direct week support is not something we care about. We have switched to our own
implementation now that fits our exact needs though.

As for everyone else _proper_ direct week support would probably _only_ allow `weeks` to be non-zero if you have _zero date_ type. E.g. imagine:

```go
type Period{
   // Allow either date or weeks
   date Date
   weeks int16
   hours, minutes, seconds int16
}

> @rickb777 want to ask, why all values in Period time multiplied by 10? Looks pretty strange honestly

I agree this looks very strange. Perhaps to support sub-second precision without a nsec parameter @rickb777?

---

Of topic, but have to mention it. `IsPositive` appear to ignore the case where the period `IsZero`. Would it not be easier to return `!p.IsNegative()`? Then it should also cover the `IsZero` case.

**Comment by quenbyako** [comment] 2021-02-25 13:36
> @smyrman: the only _purpose_ of this issue is to _prevent_ automatic normalization into weeks.

If so, why do you need so complicated `PeriodOfWeeks` type? This is worse than just renaming `New` to `NewWithWeeks` and set `New` as deprecated. I don't agree with this crutch, honestly

**Comment by smyrman** [comment] 2021-02-25 14:07
> If so, why do you need so complicated PeriodOfWeeks type?

Just saw there was a `PeriodOfDays` and copy-pasted the same logic as exists for `PeriodOfDays` in the code. It's not an important addition; just one that match the existing code for `PeriodOfDays`.

**Comment by quenbyako** [comment] 2021-02-26 13:14
@smyrman main problem of this package is that it has ambiguous `New` method, which doesn't fit even in stdlib `time` package (`time` has `Date` constructor, which is more clear naming)

I think that we have single problem for now and it is a problem with weeks. This package working amazingly well on production already (our team use it), so i don't think that it doesn't fit in RFC. One year in a row and we don't have any problems with this problem.

**Comment by smyrman** [comment] 2021-02-26 14:42
@quenbyako - I talking about the _interface_ of the proposed `New2` (not the name). 

The RFC _allows_ a format `P1W`, but does _not_ allow `P1WT1H` for instance.  I.e. if you spell out

**Comment by quenbyako** [comment] 2021-02-26 14:58
@smyrman i mean that there is no problem if the function takes in deliberately incorrect data if it formats according to the specification. what is the problem? i don't understand

**Comment by smyrman** [comment] 2021-02-26 15:16
That's the whole point, it's _not_.

The way I undertand the RFC spec (which is very brief), we got three allowed formats for the _period_ type.
```
 period = "P" (dur-date / dur-time / dur-week)
 ```
 Which I read as _one of_:
 1. `"P" + dur-date
 2.  "P" + dur-time
 3.  "P" + dur-week
 
Just using the number 1 in the example for simplicity here.
 
 Format 1 can be expanded to combine _any_ any of the params except week (in the expected order). E.g.
 - `P1Y1M1DT1H1M1.0001S`
 - `P1Y`
 - `P1MT0.001S`
 
 Format 2 can be expanded to combine any of the _time_ formats. E.g.
 -  `PT1H1M0.0001S`
 -  `PT1W`
 - `PT1M`
 - `PT1S`
 
 However, format 3 only has _one_ variant:
- `P1W`

**Comment by smyrman** [comment] 2021-02-26 15:20
But maybe I am missing something when I look at the direct week support branch?

**Comment by rickb777** [comment] 2021-03-25 22:16
I hope I can answer a few of the questions raised.

Firstly, RFC3339 only mentions durations (a.k.a periods, loosely) as a side-issue. The [Wikipedia description](https://en.wikipedia.org/wiki/ISO_8601#Durations) is more detailed and much more useful. I don't have access to the ISO standard document.

The reason they start with `P` is due to the name 'period', which may be historical. However, I've used periods like this in other languages (mainly Java) and the term used tends to be 'period' rather than 'duration' (e.g. in [JodaTime](https://www.joda.org/joda-time/key_period.html) ), so I went with that too.

The format is *not* a union of seven fields of which only one is in use. Rather it is the concatenation of seven fields. It's legitimate to have values such as `P3Y6M4DT12H30M5.2S`.

The last non-zero field may have a decimal fraction. I don't know whether a limit on the number of decimal places is defined the ISO standard; I made the design decision that a single decimal place can be easily supported. This is the reason for the x10 internal representation, which gives fixed-point values down to 0.1 without needing to use floats. The advantage of this is that two Periods can be correctly compared using `==`.

I have also experimented with different internal representations, for example having extra fields to hold the fraction, whilst keeping the main fields just integers. This might be more complex, though i might revisit it to see if there's a better fit. 

The original (and still `main` branch) implementation did not have weeks. The reason was that `time.Time` also works without weeks, e.g. `time.AddDate()` and `time.Clock()` exist but there is no `time.Week()` method. It was a mistake to omit weeks from `Period` though.

**Comment by rickb777** [comment] 2021-03-25 22:46
I merged PR#14 yesterday but I've found that there are errors and test failures. I'll roll back parts of it fixing the tests and getting rid of the floats (I've taken quite a lot of care to avoid floating point arithmetic because of conversion errors and because the period fields are almost always integers).

**Comment by rickb777** [comment] 2022-02-02 14:29
Thank you everyone for your contribution.

Resolving this was proving more tricky than I expected, mostly due to backward-compatibility issues. I have decided to re-implement period rather than continue to patch it. The new period package will be https://github.com/rickb777/period. This will incorporate your remarks indirectly.

**Comment by rickb777** [comment] 2023-11-15 14:25
Closing this issue now that the new period module is available.

**Closed by rickb777** 2023-11-15 14:25 UTC
